add metadata and fix some typo in the css
murillo-group/sarkas pull request #42
Opened 2021-11-07 10:26 UTC by SilvestriStefano

add metadata in the following pages:
+ index.rst
+ examples.rst
+ theory.rst (<-- needs description improvement)
+ get_started.rst (<-- needs description improvement)

add open graph metadata via package `sphinxext.opengraph` (check conf.py).

add missing `;` in css.

2021-11-07 10:29 UTC, SilvestriStefano commented
For more information about metadata description see : [https://moz.com/learn/seo/meta-description](url)

2021-11-09 16:24 UTC, lucianogsilvestri requested changes
Thanks a lot for your improvements. Could you make few changes before we merge it ?

2021-11-09 16:24 UTC, lucianogsilvestri commented on docs/index.rst
> +   :description: Sarkas is a fast pure-Python molecular dynamics suite for non-ideal plasmas.
Please change description to : Sarkas: A Fast pure-Python Molecular Dynamics suite for Plasma physics

2021-11-14 15:30 UTC, SilvestriStefano commented on docs/index.rst
> +   :description: Sarkas is a fast pure-Python molecular dynamics suite for non-ideal plasmas.
done.

2021-11-14 15:30 UTC, SilvestriStefano commented on docs/theory/theory.rst
> +   :description: Theory behind Sarkas.
done.

2022-05-09 22:43 UTC, merged